apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: exporter
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9158
      targetPort: 9158
