apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pingdom-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: pingdom-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: pingdom-exporter
    spec:
      containers:
      - name: exporter
        image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-pingdom-exporter

